### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by tmanson** [jamesbachini/Server-Check-PHP#1]
on line 49 you are computing the memory usage like this :
$memusage = round(($memavailable/$memtotal)*100);

I think it should be  :
 $memusage = round(($memused/$memtotal)*100);

**Comment by aavestan** [comment]
> on line 49 you are computing the memory usage like this : $memusage = round(($memavailable/$memtotal)*100);
> 
> I think it should be : $memusage = round(($memused/$memtotal)*100);
 
I think So

**Comment by jamesbachini** [comment]
Updated thank you
